export const ITALIAN_PROVINCES = [
  'Agrigento',
  'Alessandria',
  'Ancona',
  'Aosta',
  'Arezzo',
  'Ascoli Piceno',
  'Asti',
  'Avellino',
  'Bari',
  'Barletta-Andria-Trani',
  'Belluno',
  'Benevento',
  'Bergamo',
  'Biella',
  'Bologna',
  'Bolzano',
  'Brescia',
  'Brindisi',
  'Cagliari',
  'Caltanissetta',
  'Campobasso',
  'Caserta',
  'Catania',
  'Catanzaro',
  'Chieti',
  'Como',
  'Cosenza',
  'Cremona',
  'Crotone',
  'Cuneo',
  'Enna',
  'Fermo',
  'Ferrara',
  'Firenze',
  'Foggia',
  'Forlì-Cesena',
  'Frosinone',
  'Genova',
  'Gorizia',
  'Grosseto',
  'Imperia',
  'Isernia',
  'L\'Aquila',
  'La Spezia',
  'Latina',
  'Lecce',
  'Lecco',
  'Livorno',
  'Lodi',
  'Lucca',
  'Macerata',
  'Mantova',
  'Massa-Carrara',
  'Matera',
  'Messina',
  'Milano',
  'Modena',
  'Monza e Brianza',
  'Napoli',
  'Novara',
  'Nuoro',
  'Oristano',
  'Padova',
  'Palermo',
  'Parma',
  'Pavia',
  'Perugia',
  'Pesaro e Urbino',
  'Pescara',
  'Piacenza',
  'Pisa',
  'Pistoia',
  'Pordenone',
  'Potenza',
  'Prato',
  'Ragusa',
  'Ravenna',
  'Reggio Calabria',
  'Reggio Emilia',
  'Rieti',
  'Rimini',
  'Roma',
  'Rovigo',
  'Salerno',
  'Sassari',
  'Savona',
  'Siena',
  'Siracusa',
  'Sondrio',
  'Sud Sardegna',
  'Taranto',
  'Teramo',
  'Terni',
  'Torino',
  'Trapani',
  'Trento',
  'Treviso',
  'Trieste',
  'Udine',
  'Varese',
  'Venezia',
  'Verbano-Cusio-Ossola',
  'Vercelli',
  'Verona',
  'Vibo Valentia',
  'Vicenza',
  'Viterbo',
].sort();

export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  'Agrigento': ['Agrigento', 'Licata', 'Canicattì', 'Sciacca', 'Favara', 'Palma di Montechiaro', 'Ribera', 'Porto Empedocle', 'Raffadali', 'Aragona'],
  'Alessandria': ['Alessandria', 'Casale Monferrato', 'Novi Ligure', 'Tortona', 'Acqui Terme', 'Valenza', 'Ovada', 'Arquata Scrivia', 'Serravalle Scrivia', 'Castellazzo Bormida'],
  'Ancona': ['Ancona', 'Senigallia', 'Jesi', 'Fabriano', 'Osimo', 'Falconara Marittima', 'Castelfidardo', 'Chiaravalle', 'Loreto', 'Filottrano'],
  'Aosta': ['Aosta', 'Saint-Vincent', 'Châtillon', 'Pont-Saint-Martin', 'Verrès', 'Courmayeur', 'Gressan', 'Sarre', 'Arnad', 'Quart'],
  'Arezzo': ['Arezzo', 'Cortona', 'San Giovanni Valdarno', 'Montevarchi', 'Bibbiena', 'Capolona', 'Sansepolcro', 'Castiglion Fiorentino', 'Foiano della Chiana', 'Monte San Savino'],
  'Ascoli Piceno': ['Ascoli Piceno', 'San Benedetto del Tronto', 'Grottammare', 'Montegranaro', 'Acquaviva Picena', 'Castel di Lama', 'Spinetoli', 'Folignano', 'Cupra Marittima', 'Colli del Tronto'],
  'Asti': ['Asti', 'Canelli', 'Nizza Monferrato', 'Villanova d\'Asti', 'San Damiano d\'Asti', 'Moncalieri', 'Costigliole d\'Asti', 'Castelnuovo Don Bosco', 'Incisa Scapaccino', 'Montegrosso d\'Asti'],
  'Avellino': ['Avellino', 'Ariano Irpino', 'Atripalda', 'Cervinara', 'Mercogliano', 'Monteforte Irpino', 'Solofra', 'Montoro', 'Grottaminarda', 'Avella'],
  'Bari': ['Bari', 'Altamura', 'Molfetta', 'Monopoli', 'Bitonto', 'Corato', 'Putignano', 'Gravina in Puglia', 'Triggiano', 'Modugno'],
  'Barletta-Andria-Trani': ['Barletta', 'Andria', 'Trani', 'Bisceglie', 'Canosa di Puglia', 'Margherita di Savoia', 'Trinitapoli', 'San Ferdinando di Puglia', 'Minervino Murge', 'Spinazzola'],
  'Belluno': ['Belluno', 'Feltre', 'Sedico', 'Ponte nelle Alpi', 'Santa Giustina', 'Agordo', 'Longarone', 'Cortina d\'Ampezzo', 'Pieve di Cadore', 'Mel'],
  'Benevento': ['Benevento', 'Montesarchio', 'Sant\'Agata de\' Goti', 'Airola', 'Telese Terme', 'San Giorgio del Sannio', 'Apollosa', 'Dugenta', 'Moiano', 'Solopaca'],
  'Bergamo': ['Bergamo', 'Treviglio', 'Seriate', 'Dalmine', 'Romano di Lombardia', 'Albino', 'Caravaggio', 'Alzano Lombardo', 'Stezzano', 'Osio Sotto'],
  'Biella': ['Biella', 'Cossato', 'Candelo', 'Gaglianico', 'Valduggia', 'Andorno Micca', 'Cavaglià', 'Trivero', 'Vigliano Biellese', 'Mosso'],
  'Bologna': ['Bologna', 'Imola', 'Casalecchio di Reno', 'San Lazzaro di Savena', 'Castel San Pietro Terme', 'Castel Maggiore', 'Borgo Tossignano', 'Zola Predosa', 'San Giovanni in Persiceto', 'Molinella'],
  'Bolzano': ['Bolzano', 'Merano', 'Bressanone', 'Brunico', 'Laives', 'Egna', 'Vipiteno', 'Appiano sulla Strada del Vino', 'Chiusa', 'Silandro'],
  'Brescia': ['Brescia', 'Desenzano del Garda', 'Montichiari', 'Lumezzane', 'Palazzolo sull\'Oglio', 'Manerbio', 'Chiari', 'Rezzato', 'Ghedi', 'Rovato'],
  'Brindisi': ['Brindisi', 'Francavilla Fontana', 'Fasano', 'Ostuni', 'Mesagne', 'San Vito dei Normanni', 'Ceglie Messapica', 'Latiano', 'San Pietro Vernotico', 'Carovigno'],
  'Cagliari': ['Cagliari', 'Quartu Sant\'Elena', 'Assemini', 'Selargius', 'Capoterra', 'Sestu', 'Monserrato', 'Quartucciu', 'Sinnai', 'Elmas'],
  'Caltanissetta': ['Caltanissetta', 'Gela', 'Niscemi', 'Mussomeli', 'San Cataldo', 'Mazzarino', 'Riesi', 'Sommatino', 'Serradifalco', 'Butera'],
  'Campobasso': ['Campobasso', 'Termoli', 'Isernia', 'Larino', 'Venafro', 'Bojano', 'Campomarino', 'Riccia', 'Guglionesi', 'Santa Croce di Magliano'],
  'Caserta': ['Caserta', 'Aversa', 'Marcianise', 'Maddaloni', 'Santa Maria Capua Vetere', 'Mondragone', 'San Nicola la Strada', 'Capua', 'Orta di Atella', 'Recale'],
  'Catania': ['Catania', 'Acireale', 'Misterbianco', 'Paternò', 'Adrano', 'Mascalucia', 'Belpasso', 'Giarre', 'Gravina di Catania', 'Caltagirone'],
  'Catanzaro': ['Catanzaro', 'Lamezia Terme', 'Soverato', 'Sellia Marina', 'Chiaravalle Centrale', 'Girifalco', 'Squillace', 'Cropani', 'Simeri Crichi', 'Davoli'],
  'Chieti': ['Chieti', 'Vasto', 'Lanciano', 'Francavilla al Mare', 'Ortona', 'San Salvo', 'Guardiagrele', 'Atessa', 'San Giovanni Teatino', 'Casoli'],
  'Como': ['Como', 'Cantù', 'Erba', 'Mariano Comense', 'Olgiate Comasco', 'Lomazzo', 'Lurate Caccivio', 'Menaggio', 'Cernobbio', 'Lipomo'],
  'Cosenza': ['Cosenza', 'Rende', 'Corigliano-Rossano', 'Castrovillari', 'Paola', 'Montalto Uffugo', 'San Giovanni in Fiore', 'Acri', 'Cassano all\'Ionio', 'Corigliano Calabro'],
  'Cremona': ['Cremona', 'Crema', 'Casalmaggiore', 'Soresina', 'Castelleone', 'Pizzighettone', 'Pandino', 'Rivolta d\'Adda', 'Spino d\'Adda', 'Ostiano'],
  'Crotone': ['Crotone', 'Cirò Marina', 'Cutro', 'Isola di Capo Rizzuto', 'Petilia Policastro', 'Mesoraca', 'Rocca di Neto', 'Strongoli', 'Scandale', 'Cotronei'],
  'Cuneo': ['Cuneo', 'Alba', 'Bra', 'Fossano', 'Mondovì', 'Savigliano', 'Saluzzo', 'Borgo San Dalmazzo', 'Racconigi', 'Busca'],
  'Enna': ['Enna', 'Piazza Armerina', 'Leonforte', 'Nicosia', 'Barrafranca', 'Agira', 'Centuripe', 'Valguarnera Caropepe', 'Aidone', 'Regalbuto'],
  'Fermo': ['Fermo', 'Porto Sant\'Elpidio', 'Sant\'Elpidio a Mare', 'Porto San Giorgio', 'Montegranaro', 'Monte Urano', 'Montegiorgio', 'Civitanova Marche', 'Amandola', 'Grottazzolina'],
  'Ferrara': ['Ferrara', 'Cento', 'Comacchio', 'Argenta', 'Bondeno', 'Codigoro', 'Copparo', 'Portomaggiore', 'Lido degli Estensi', 'Mesola'],
  'Firenze': ['Firenze', 'Sesto Fiorentino', 'Scandicci', 'Empoli', 'Campi Bisenzio', 'Figline e Incisa Valdarno', 'Bagno a Ripoli', 'Borgo San Lorenzo', 'Pontassieve', 'Lastra a Signa'],
  'Foggia': ['Foggia', 'Cerignola', 'Manfredonia', 'San Severo', 'Lucera', 'Orta Nova', 'Apricena', 'San Giovanni Rotondo', 'Torremaggiore', 'Vieste'],
  'Forlì-Cesena': ['Forlì', 'Cesena', 'Cesenatico', 'Forlimpopoli', 'Savignano sul Rubicone', 'Gatteo', 'Bertinoro', 'Meldola', 'San Mauro Pascoli', 'Castrocaro Terme'],
  'Frosinone': ['Frosinone', 'Cassino', 'Sora', 'Ceccano', 'Alatri', 'Ferentino', 'Anagni', 'Pontecorvo', 'Veroli', 'Monte San Giovanni Campano'],
  'Genova': ['Genova', 'Chiavari', 'Rapallo', 'Sestri Levante', 'Lavagna', 'Recco', 'Arenzano', 'Cogoleto', 'Camogli', 'Santa Margherita Ligure'],
  'Gorizia': ['Gorizia', 'Monfalcone', 'Gradisca d\'Isonzo', 'Grado', 'Cormons', 'Ronchi dei Legionari', 'Staranzano', 'San Canzian d\'Isonzo', 'Fogliano Redipuglia', 'Turriaco'],
  'Grosseto': ['Grosseto', 'Follonica', 'Orbetello', 'Massa Marittima', 'Castiglione della Pescaia', 'Roccastrada', 'Monte Argentario', 'Manciano', 'Gavorrano', 'Pitigliano'],
  'Imperia': ['Imperia', 'Sanremo', 'Ventimiglia', 'Bordighera', 'Taggia', 'Diano Marina', 'Camporosso', 'Arma di Taggia', 'Vallecrosia', 'Riva Ligure'],
  'Isernia': ['Isernia', 'Venafro', 'Agnone', 'Bojano', 'Miranda', 'Pozzilli', 'Macchia d\'Isernia', 'Pettoranello del Molise', 'Roccamandolfi', 'Santa Maria del Molise'],
  'L\'Aquila': ['L\'Aquila', 'Avezzano', 'Sulmona', 'Celano', 'Pratola Peligna', 'Tagliacozzo', 'Carsoli', 'Trasacco', 'Castel di Sangro', 'Luco dei Marsi'],
  'La Spezia': ['La Spezia', 'Sarzana', 'Lerici', 'Vezzano Ligure', 'Santo Stefano di Magra', 'Arcola', 'Ortonovo', 'Levanto', 'Portovenere', 'Castelnuovo Magra'],
  'Latina': ['Latina', 'Aprilia', 'Terracina', 'Formia', 'Cisterna di Latina', 'Fondi', 'Sabaudia', 'Pontinia', 'Sezze', 'Gaeta'],
  'Lecce': ['Lecce', 'Nardò', 'Copertino', 'Galatina', 'Casarano', 'Gallipoli', 'Trepuzzi', 'Squinzano', 'Surbo', 'Tricase'],
  'Lecco': ['Lecco', 'Merate', 'Calolziocorte', 'Bellano', 'Mandello del Lario', 'Oggiono', 'Olginate', 'Barzanò', 'Casatenovo', 'Colico'],
  'Livorno': ['Livorno', 'Piombino', 'Cecina', 'Rosignano Marittimo', 'Portoferraio', 'Collesalvetti', 'Campiglia Marittima', 'Castagneto Carducci', 'San Vincenzo', 'Venturina Terme'],
  'Lodi': ['Lodi', 'Casalpusterlengo', 'Sant\'Angelo Lodigiano', 'Codogno', 'Lodi Vecchio', 'Tavazzano con Villavesco', 'Casaletto Lodigiano', 'Zelo Buon Persico', 'Massalengo', 'Borghetto Lodigiano'],
  'Lucca': ['Lucca', 'Viareggio', 'Capannori', 'Camaiore', 'Pietrasanta', 'Massarosa', 'Altopascio', 'Porcari', 'Forte dei Marmi', 'Borgo a Mozzano'],
  'Macerata': ['Macerata', 'Civitanova Marche', 'Corridonia', 'Recanati', 'Tolentino', 'Potenza Picena', 'Porto Recanati', 'Morrovalle', 'Montecosaro', 'Mogliano'],
  'Mantova': ['Mantova', 'Castiglione delle Stiviere', 'Suzzara', 'Viadana', 'Asola', 'Castel Goffredo', 'Gonzaga', 'Porto Mantovano', 'Guidizzolo', 'Virgilio'],
  'Massa-Carrara': ['Massa', 'Carrara', 'Montignoso', 'Fivizzano', 'Aulla', 'Pontremoli', 'Fosdinovo', 'Marina di Massa', 'Licciana Nardi', 'Villafranca in Lunigiana'],
  'Matera': ['Matera', 'Pisticci', 'Policoro', 'Montalbano Jonico', 'Nova Siri', 'Bernalda', 'Scanzano Jonico', 'Tursi', 'Stigliano', 'Ferrandina'],
  'Messina': ['Messina', 'Barcellona Pozzo di Gotto', 'Milazzo', 'Patti', 'Sant\'Agata di Militello', 'Taormina', 'Lipari', 'Giardini-Naxos', 'Capo d\'Orlando', 'Spadafora'],
  'Milano': ['Milano', 'Sesto San Giovanni', 'Cinisello Balsamo', 'Rho', 'Cologno Monzese', 'Legnano', 'Paderno Dugnano', 'Bollate', 'Monza', 'Corsico'],
  'Modena': ['Modena', 'Carpi', 'Sassuolo', 'Formigine', 'Vignola', 'Castelfranco Emilia', 'Mirandola', 'Fiorano Modenese', 'Maranello', 'Pavullo nel Frignano'],
  'Monza e Brianza': ['Monza', 'Desio', 'Seregno', 'Lissone', 'Limbiate', 'Cesano Maderno', 'Vimercate', 'Muggiò', 'Brugherio', 'Giussano'],
  'Napoli': ['Napoli', 'Torre del Greco', 'Pozzuoli', 'Giugliano in Campania', 'Castellammare di Stabia', 'Afragola', 'Marano di Napoli', 'Portici', 'Ercolano', 'Acerra'],
  'Novara': ['Novara', 'Borgomanero', 'Arona', 'Galliate', 'Trecate', 'Oleggio', 'Cameri', 'Castelletto sopra Ticino', 'Granozzo con Monticello', 'Romentino'],
  'Nuoro': ['Nuoro', 'Siniscola', 'Macomer', 'Dorgali', 'Orosei', 'Bitti', 'Tortolì', 'Fonni', 'Oliena', 'Orune'],
  'Oristano': ['Oristano', 'Terralba', 'Cabras', 'Ghilarza', 'Bosa', 'Marrubiu', 'Santa Giusta', 'Ales', 'Cuglieri', 'Abbasanta'],
  'Padova': ['Padova', 'Abano Terme', 'Cittadella', 'Monselice', 'Piove di Sacco', 'Este', 'Cadoneghe', 'Vigonza', 'Selvazzano Dentro', 'Albignasego'],
  'Palermo': ['Palermo', 'Bagheria', 'Carini', 'Partinico', 'Monreale', 'Termini Imerese', 'Misilmeri', 'Villabate', 'Ficarazzi', 'Cinisi'],
  'Parma': ['Parma', 'Fidenza', 'Collecchio', 'Salsomaggiore Terme', 'Langhirano', 'Noceto', 'Medesano', 'Traversetolo', 'Fontanellato', 'Fornovo di Taro'],
  'Pavia': ['Pavia', 'Vigevano', 'Voghera', 'Mortara', 'Stradella', 'Casteggio', 'Broni', 'Garlasco', 'Siziano', 'Belgioioso'],
  'Perugia': ['Perugia', 'Foligno', 'Città di Castello', 'Gubbio', 'Assisi', 'Spoleto', 'Bastia Umbra', 'Corciano', 'Terni', 'Umbertide'],
  'Pesaro e Urbino': ['Pesaro', 'Fano', 'Urbino', 'Fossombrone', 'Gabicce Mare', 'Mondolfo', 'Marotta', 'Cattolica', 'Pergola', 'Cagli'],
  'Pescara': ['Pescara', 'Montesilvano', 'Spoltore', 'Città Sant\'Angelo', 'Penne', 'Popoli', 'Manoppello', 'Loreto Aprutino', 'Cappelle sul Tavo', 'Pianella'],
  'Piacenza': ['Piacenza', 'Castel San Giovanni', 'Fiorenzuola d\'Arda', 'Rottofreno', 'Podenzano', 'Carpaneto Piacentino', 'Borgonovo Val Tidone', 'Cortemaggiore', 'Rivergaro', 'Cadeo'],
  'Pisa': ['Pisa', 'Pontedera', 'Volterra', 'San Giuliano Terme', 'Cascina', 'Vecchiano', 'Ponsacco', 'Santa Croce sull\'Arno', 'Calci', 'San Miniato'],
  'Pistoia': ['Pistoia', 'Montecatini Terme', 'Quarrata', 'Agliana', 'Monsummano Terme', 'Pescia', 'Serravalle Pistoiese', 'Montale', 'Lamporecchio', 'Pieve a Nievole'],
  'Pordenone': ['Pordenone', 'Sacile', 'Maniago', 'Aviano', 'Azzano Decimo', 'Fontanafredda', 'Spilimbergo', 'Cordenons', 'San Vito al Tagliamento', 'Brugnera'],
  'Potenza': ['Potenza', 'Melfi', 'Lavello', 'Lauria', 'Rionero in Vulture', 'Venosa', 'Avigliano', 'Senise', 'Pignola', 'Bella'],
  'Prato': ['Prato', 'Montemurlo', 'Carmignano', 'Poggio a Caiano', 'Vaiano', 'Vernio', 'Cantagallo', 'Prato Centro', 'Galciana', 'Tavola'],
  'Ragusa': ['Ragusa', 'Vittoria', 'Modica', 'Comiso', 'Scicli', 'Pozzallo', 'Ispica', 'Acate', 'Santa Croce Camerina', 'Chiaramonte Gulfi'],
  'Ravenna': ['Ravenna', 'Faenza', 'Lugo', 'Cervia', 'Russi', 'Bagnacavallo', 'Alfonsine', 'Brisighella', 'Castel Bolognese', 'Conselice'],
  'Reggio Calabria': ['Reggio Calabria', 'Gioia Tauro', 'Palmi', 'Siderno', 'Villa San Giovanni', 'Melito di Porto Salvo', 'Taurianova', 'Polistena', 'Bovalino', 'Locri'],
  'Reggio Emilia': ['Reggio Emilia', 'Correggio', 'Scandiano', 'Guastalla', 'Casalgrande', 'Castelnovo ne\' Monti', 'Rubiera', 'Montecchio Emilia', 'Novellara', 'Cavriago'],
  'Rieti': ['Rieti', 'Poggio Mirteto', 'Fara in Sabina', 'Cittaducale', 'Magliano Sabina', 'Leonessa', 'Amatrice', 'Cantalice', 'Borgorose', 'Stimigliano'],
  'Rimini': ['Rimini', 'Riccione', 'Cattolica', 'Bellaria-Igea Marina', 'Santarcangelo di Romagna', 'San Giovanni in Marignano', 'Misano Adriatico', 'Verucchio', 'Coriano', 'Morciano di Romagna'],
  'Roma': ['Roma', 'Fiumicino', 'Guidonia Montecelio', 'Ardea', 'Pomezia', 'Tivoli', 'Anzio', 'Ciampino', 'Velletri', 'Monterotondo'],
  'Rovigo': ['Rovigo', 'Adria', 'Porto Viro', 'Lendinara', 'Badia Polesine', 'Occhiobello', 'Porto Tolle', 'Taglio di Po', 'Villamarzana', 'Loreo'],
  'Salerno': ['Salerno', 'Cava de\' Tirreni', 'Battipaglia', 'Eboli', 'Nocera Inferiore', 'Pagani', 'Scafati', 'Agropoli', 'Sarno', 'Pontecagnano Faiano'],
  'Sassari': ['Sassari', 'Alghero', 'Olbia', 'Tempio Pausania', 'Porto Torres', 'Sorso', 'La Maddalena', 'Arzachena', 'Ozieri', 'Stintino'],
  'Savona': ['Savona', 'Albenga', 'Cairo Montenotte', 'Varazze', 'Finale Ligure', 'Loano', 'Alassio', 'Carcare', 'Albisola Superiore', 'Pietra Ligure'],
  'Siena': ['Siena', 'Poggibonsi', 'Colle di Val d\'Elsa', 'Montepulciano', 'Sinalunga', 'Abbadia San Salvatore', 'Sovicille', 'Montalcino', 'Chiusi', 'Asciano'],
  'Siracusa': ['Siracusa', 'Augusta', 'Avola', 'Noto', 'Lentini', 'Pachino', 'Floridia', 'Priolo Gargallo', 'Rosolini', 'Carlentini'],
  'Sondrio': ['Sondrio', 'Morbegno', 'Tirano', 'Livigno', 'Chiavenna', 'Bormio', 'Ponte in Valtellina', 'Berbenno di Valtellina', 'Sondalo', 'Teglio'],
  'Sud Sardegna': ['Carbonia', 'Iglesias', 'Guspini', 'Portoscuso', 'Villasor', 'San Gavino Monreale', 'Sant\'Antioco', 'Domusnovas', 'Santadi', 'Musei'],
  'Taranto': ['Taranto', 'Martina Franca', 'Manduria', 'Massafra', 'Grottaglie', 'Castellaneta', 'Ginosa', 'Francavilla Fontana', 'Crispiano', 'Palagiano'],
  'Teramo': ['Teramo', 'Giulianova', 'Roseto degli Abruzzi', 'Pineto', 'Silvi', 'Atri', 'Alba Adriatica', 'Martinsicuro', 'Sant\'Egidio alla Vibrata', 'Tortoreto'],
  'Terni': ['Terni', 'Orvieto', 'Narni', 'Amelia', 'Spoleto', 'Foligno', 'Marsciano', 'San Gemini', 'Acquasparta', 'Fabro'],
  'Torino': ['Torino', 'Moncalieri', 'Rivoli', 'Collegno', 'Settimo Torinese', 'Nichelino', 'Chieri', 'Ivrea', 'Pinerolo', 'Grugliasco'],
  'Trapani': ['Trapani', 'Marsala', 'Mazara del Vallo', 'Alcamo', 'Castelvetrano', 'Erice', 'Partanna', 'Salemi', 'Campobello di Mazara', 'Castellammare del Golfo'],
  'Trento': ['Trento', 'Rovereto', 'Pergine Valsugana', 'Arco', 'Riva del Garda', 'Lavis', 'Mori', 'Ala', 'Levico Terme', 'Cles'],
  'Treviso': ['Treviso', 'Conegliano', 'Vittorio Veneto', 'Montebelluna', 'Castelfranco Veneto', 'Mogliano Veneto', 'Paese', 'Oderzo', 'Preganziol', 'Villorba'],
  'Trieste': ['Trieste', 'Muggia', 'San Dorligo della Valle', 'Sgonico', 'Duino-Aurisina', 'Monrupino', 'San Giorgio di Nogaro', 'Grignano', 'Prosecco', 'Sistiana'],
  'Udine': ['Udine', 'Cividale del Friuli', 'Codroipo', 'Gemona del Friuli', 'Tavagnacco', 'Latisana', 'Tolmezzo', 'Palmanova', 'Lignano Sabbiadoro', 'San Daniele del Friuli'],
  'Varese': ['Varese', 'Busto Arsizio', 'Gallarate', 'Saronno', 'Tradate', 'Cassano Magnago', 'Luino', 'Malnate', 'Somma Lombardo', 'Gavirate'],
  'Venezia': ['Venezia', 'Mestre', 'Chioggia', 'San Donà di Piave', 'Marghera', 'Mira', 'Spinea', 'Mirano', 'Jesolo', 'Portogruaro'],
  'Verbano-Cusio-Ossola': ['Verbania', 'Domodossola', 'Omegna', 'Gravellona Toce', 'Villadossola', 'Baveno', 'Cannobio', 'Stresa', 'Premosello-Chiovenda', 'Crevoladossola'],
  'Vercelli': ['Vercelli', 'Borgosesia', 'Santhià', 'Trino', 'Gattinara', 'Cigliano', 'Crescentino', 'Varallo', 'Livorno Ferraris', 'Borgomanero'],
  'Verona': ['Verona', 'Villafranca di Verona', 'San Giovanni Lupatoto', 'Legnago', 'Bussolengo', 'San Bonifacio', 'Bardolino', 'Pescantina', 'Sommacampagna', 'Cerea'],
  'Vibo Valentia': ['Vibo Valentia', 'Tropea', 'Pizzo', 'Serra San Bruno', 'Mileto', 'Soriano Calabro', 'Filadelfia', 'Nicotera', 'Briatico', 'Jonadi'],
  'Vicenza': ['Vicenza', 'Bassano del Grappa', 'Schio', 'Arzignano', 'Valdagno', 'Thiene', 'Montecchio Maggiore', 'Lonigo', 'Nove', 'Torri di Quartesolo'],
  'Viterbo': ['Viterbo', 'Civita Castellana', 'Montefiascone', 'Tarquinia', 'Orte', 'Acquapendente', 'Tuscania', 'Vetralla', 'Sutri', 'Nepi'],
};
