import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  it: {
    // Header
    'header.search': 'Cerca attività...',
    'header.home': 'Home',
    'header.products': 'Prodotti',
    'header.classifieds': 'Annunci',
    'header.jobs': 'Lavoro',
    'header.discounts': 'Sconti',
    'header.solidarity': 'Solidarietà',
    'header.leaderboard': 'Classifica',
    'header.notifications': 'Notifiche',
    'header.messages': 'Messaggi',
    'header.profile': 'Profilo',
    'header.dashboard': 'Dashboard',
    'header.logout': 'Esci',
    'header.login': 'Accedi',
    'header.register': 'Registrati',
    'header.contact': 'Contatti',
    'header.contacts': 'Contatti',
    'header.plans': 'Piani',
    'header.subscription': 'Abbonamenti',
    'header.rules': 'Regole',
    'header.myProfile': 'Mio Profilo',
    'header.location': 'Sede',
    'header.selectedLocation': 'Sede selezionata',

    // Leaderboard
    'leaderboard.title': 'Classifica & Premi',
    'leaderboard.subtitle': 'Visualizza la tua posizione nella classifica Top 20 e scopri i premi disponibili',
    'leaderboard.tab.leaderboard': 'Classifica',
    'leaderboard.tab.activity': 'La Mia Attività',
    'leaderboard.tab.rewards': 'Premi',
    'leaderboard.yourPosition': 'La tua posizione',
    'leaderboard.points': 'punti',
    'leaderboard.reviews': 'recensioni',
    'leaderboard.prizesTitle': 'Premi in Palio',
    'leaderboard.prizesDescription': 'I migliori 20 utenti privati dell\'anno riceveranno gift card da 50€ a 500€. La classifica è pubblica per garantire massima trasparenza nella competizione. Continua a scrivere recensioni verificate per scalare la classifica e vincere premi fantastici!',
    'leaderboard.top20': 'Top 20 Utenti',
    'leaderboard.filter.all': 'Tutti',
    'leaderboard.filter.private': 'Privati',
    'leaderboard.filter.business': 'Professionisti',
    'leaderboard.noUsers': 'Nessun utente in classifica',
    'leaderboard.loading': 'Caricamento classifica...',
    'leaderboard.howToEarnCustomer': 'Come Guadagnare Punti - Utenti Privati e Membri Famiglia',
    'leaderboard.howToEarnBusiness': 'Come Guadagnare Punti - Professionisti',
    'leaderboard.allUsersEarn': 'Tutti gli utenti (profilo principale e membri della famiglia) guadagnano punti allo stesso modo:',
    'leaderboard.businessEarn': 'I professionisti guadagnano punti in base alle recensioni ricevute dai clienti e alle attività pubblicate.',
    'leaderboard.pointsNote': 'I punti delle recensioni vengono assegnati dopo l\'approvazione dello staff. Ogni utente compete individualmente nella classifica, inclusi i membri della famiglia.',
    'leaderboard.businessNote': 'I punti delle recensioni vengono assegnati solo dopo l\'approvazione dello staff. Maggiore è la qualità del servizio, maggiori saranno i punti guadagnati.',

    // Points
    'points.completeReview': 'per recensione completa (con valutazioni dettagliate)',
    'points.referral': 'quando un amico si abbona usando il tuo nickname',
    'points.basicReview': 'per recensione base (solo voto finale)',
    'points.addBusiness': 'per inserimento di un\'attività non presente',
    'points.addProduct': 'per ogni prodotto inserito',
    'points.addClassified': 'per ogni annuncio pubblicato',
    'points.review1star': 'per recensione a 1 stella ricevuta',
    'points.review2star': 'per recensione a 2 stelle ricevuta',
    'points.review3star': 'per recensione a 3 stelle ricevuta',
    'points.review4star': 'per recensione a 4 stelle ricevuta',
    'points.review5star': 'per recensione a 5 stelle ricevuta',
    'points.jobPosting': 'per ogni annuncio di lavoro pubblicato',

    // Rewards
    'rewards.customersTitle': 'Premi per Utenti Privati',
    'rewards.customersDescription': 'I migliori 20 utenti privati dell\'anno riceveranno fantastici premi in gift card.',
    'rewards.customersSubtitle': 'Continua a guadagnare punti scrivendo recensioni verificate con foto e dettagli. Maggiore è il tuo contributo alla community, maggiori saranno le tue possibilità di vincere!',
    'rewards.businessTitle': 'Premi per Professionisti',
    'rewards.businessDescription': 'I migliori 20 professionisti dell\'anno riceveranno riconoscimenti speciali per la loro eccellenza nel servizio clienti.',
    'rewards.businessSubtitle': 'Ricevi recensioni positive e scala la classifica per ottenere visibilità e premi esclusivi!',
    'rewards.1stPlace': '1° Posto',
    'rewards.2ndPlace': '2° Posto',
    'rewards.3rdPlace': '3° Posto',
    'rewards.4to5Place': '4° - 5° Posto',
    'rewards.6to10Place': '6° - 10° Posto',
    'rewards.11to20Place': '11° - 20° Posto',
    'rewards.2to5Place': '2° - 5° Posto',
    'rewards.6to20Place': '6° - 20° Posto',
    'rewards.giftCard500': 'Gift card da 500€',
    'rewards.giftCard200': 'Gift card da 200€',
    'rewards.giftCard150': 'Gift card da 150€',
    'rewards.giftCard100': 'Gift card da 100€',
    'rewards.giftCard75': 'Gift card da 75€',
    'rewards.giftCard50': 'Gift card da 50€',
    'rewards.giftCardNote': 'Le gift card potranno essere scelte tra una lista di brand e servizi che verrà pubblicata in seguito.',
    'rewards.excellenceCertificate': 'Certificato Eccellenza + Visibilità Premium',
    'rewards.qualityBadge': 'Badge Qualità + Promozione Premium',
    'rewards.recognitionBadge': 'Badge Riconoscimento + Visibilità Extra',
    'rewards.availableBadges': 'Badge Disponibili',
    'rewards.pointsRequired': 'punti richiesti',

    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.close': 'Chiudi',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.back': 'Indietro',
    'common.view': 'Visualizza',
    'common.submit': 'Invia',
    'common.apply': 'Applica',

    // HomePage
    'home.welcomeTo': 'Benvenuto su',
    'home.platformName': 'Trovafacile',
    'home.tagline': 'La piattaforma italiana che connette cittadini e attività locali.',
    'home.subtitle': 'Recensioni verificate, prodotti, annunci, lavoro e solidarietà in un unico posto.',
    'home.trialInfo': 'Un mese di prova gratuito per tutti! Poi a partire da €0.49/mese per privati e €2.49/mese + IVA per attività.',
    'home.startFree': 'Inizia Gratis',
    'home.viewPlans': 'Vedi i Piani',
    'home.whatCanYouDo': 'Cosa puoi fare con Trovafacile',
    'home.completeDescription': 'Una piattaforma completa per tutte le tue esigenze quotidiane',
    'home.feature.search.title': 'Cerca Attività',
    'home.feature.search.description': 'Trova facilmente attività commerciali nella tua zona. Cerca per categoria, città o nome e scopri i migliori servizi vicino a te.',
    'home.feature.reviews.title': 'Recensioni Verificate',
    'home.feature.reviews.description': 'Leggi e scrivi recensioni autentiche. Solo utenti verificati possono lasciare feedback, garantendo massima trasparenza e affidabilità.',
    'home.feature.prizes.title': 'Vinci Premi',
    'home.feature.prizes.description': 'Scrivi recensioni e accumula punti! I migliori 20 utenti dell\'anno vincono gift card ricaricabili. Più recensioni scrivi, più premi vinci!',
    'home.feature.products.title': 'Prodotti Locali',
    'home.feature.products.description': 'Scopri i prodotti delle attività locali. Confronta prezzi, leggi recensioni e trova esattamente quello che cerchi nel tuo territorio.',
    'home.feature.classifieds.title': 'Annunci Gratuiti',
    'home.feature.classifieds.description': 'Pubblica e cerca annunci di compravendita, scambio o donazione. Connettiti con altri utenti e scambia oggetti nella tua comunità.',
    'home.feature.jobs.title': 'Offerte di Lavoro',
    'home.feature.jobs.description': 'Cerca lavoro o pubblica annunci. Le attività possono trovare candidati qualificati e i lavoratori possono scoprire opportunità locali.',
    'home.leaderboard.title': 'Classifica Utenti con Premi Esclusivi',
    'home.leaderboard.description': 'Scrivi recensioni (utenti privati) e ricevi recensioni (professionisti) per scalare la classifica! I migliori 20 utenti dell\'anno riceveranno gift card ricaricabili come premio per il loro contributo. Più recensioni scrivi con foto e dettagli, più punti guadagni!',
    'home.solidarity.title': 'Solidarietà: Il 10% del Fatturato in Beneficenza',
    'home.solidarity.description1': 'Trovafacile dona ogni anno il',
    'home.solidarity.percentage': '10% del proprio fatturato',
    'home.solidarity.description2': 'ad associazioni no profit e progetti di beneficenza scelti dai nostri iscritti con un sondaggio.',
    'home.solidarity.transparency': 'Tutti i documenti che attestano il fatturato e le donazioni sono pubblicati nella sezione Solidarietà per garantire massima trasparenza.',
    'home.forIndividuals': 'Per i Privati',
    'home.forBusiness': 'Per le Attività',
    'home.startingFrom': 'A partire da',
    'home.perMonth': '/mese',
    'home.trialFree': 'Un mese di prova gratuito',
    'home.plusVAT': '+ IVA',
    'home.feature.findBusinesses': 'Trova attività verificate nella tua zona',
    'home.feature.findProducts': 'Trova prodotti di ogni genere',
    'home.feature.writeReviews': 'Scrivi recensioni e vinci premi',
    'home.feature.exclusiveDiscounts': 'Accedi a sconti esclusivi delle attività',
    'home.feature.freeAds': 'Pubblica annunci gratuiti',
    'home.feature.jobSearch': 'Cerca offerte di lavoro locali',
    'home.feature.charity': 'Il 10% andrà in beneficenza',
    'home.feature.increaseVisibility': 'Aumenta la visibilità della tua attività',
    'home.feature.manageReviews': 'Gestisci recensioni e rispondi ai clienti',
    'home.feature.addProducts': 'Aggiungi prodotti e servizi alla tua vetrina',
    'home.feature.exclusiveOffers': 'Crea sconti esclusivi per i clienti',
    'home.feature.publishJobs': 'Pubblica offerte di lavoro e trova personale',
    'home.feature.multipleLocations': 'Gestisci più sedi dalla stessa piattaforma',
    'home.feature.analytics': 'Statistiche e analytics dettagliati',
    'home.startNow': 'Inizia Ora',
    'home.viewDetails': 'Vedi Dettagli',
    'home.topBusinesses': 'Le Attività Più Votate',

    // ContactPage
    'contact.title': 'Contattaci',
    'contact.subtitle': 'Hai domande o suggerimenti? Siamo qui per aiutarti',
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.hours': 'Orari di Supporto',
    'contact.hoursCopy': 'Lun-Ven: 9:00-18:00',
    'contact.faq': 'Domande Frequenti',

    // SubscriptionPage
    'subscription.title': 'Scegli il Tuo Piano',
    'subscription.subtitle': 'Inizia con 1 mese di prova gratuito',
    'subscription.forCustomers': 'Per Privati',
    'subscription.forBusiness': 'Per Attività',
    'subscription.month': '/mese',
    'subscription.popular': 'Popolare',
    'subscription.current': 'Piano Attuale',
    'subscription.choosePlan': 'Scegli Piano',
    'subscription.features': 'Caratteristiche',
    'subscription.trialNote': 'Tutti i piani includono 1 mese di prova gratuito',

    // RulesPage
    'rules.title': 'Regolamento della Piattaforma',
    'rules.subtitle': 'Linee guida per l\'utilizzo di Trovafacile',
    'rules.conduct': 'Codice di Condotta',
    'rules.reviews': 'Recensioni',
    'rules.businesses': 'Attività Commerciali',
    'rules.privacy': 'Privacy e Sicurezza',

    // ProfilePage
    'profile.title': 'Il Mio Profilo',
    'profile.personalInfo': 'Informazioni Personali',
    'profile.editProfile': 'Modifica Profilo',
    'profile.familyMembers': 'Membri Famiglia',
    'profile.addMember': 'Aggiungi Membro',
    'profile.businessInfo': 'Informazioni Attività',
    'profile.locations': 'Sedi',
    'profile.subscription': 'Abbonamento',
    'profile.settings': 'Impostazioni',
    'profile.logout': 'Esci',

    // DashboardPage
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Benvenuto',
    'dashboard.overview': 'Panoramica',
    'dashboard.stats': 'Statistiche',
    'dashboard.recentActivity': 'Attività Recente',
    'dashboard.quickActions': 'Azioni Rapide',
    'dashboard.reviews': 'Recensioni',
    'dashboard.products': 'Prodotti',
    'dashboard.classifieds': 'Annunci',
    'dashboard.jobs': 'Offerte di Lavoro',
    'dashboard.discounts': 'Sconti',
  },
  en: {
    // Header
    'header.search': 'Search business...',
    'header.home': 'Home',
    'header.products': 'Products',
    'header.classifieds': 'Classifieds',
    'header.jobs': 'Jobs',
    'header.discounts': 'Discounts',
    'header.solidarity': 'Solidarity',
    'header.leaderboard': 'Leaderboard',
    'header.notifications': 'Notifications',
    'header.messages': 'Messages',
    'header.profile': 'Profile',
    'header.dashboard': 'Dashboard',
    'header.logout': 'Logout',
    'header.login': 'Login',
    'header.register': 'Register',
    'header.contact': 'Contact',
    'header.contacts': 'Contacts',
    'header.plans': 'Plans',
    'header.subscription': 'Subscription',
    'header.rules': 'Rules',
    'header.myProfile': 'My Profile',
    'header.location': 'Location',
    'header.selectedLocation': 'Selected location',

    // Leaderboard
    'leaderboard.title': 'Leaderboard & Prizes',
    'leaderboard.subtitle': 'View your position in the Top 20 leaderboard and discover available prizes',
    'leaderboard.tab.leaderboard': 'Leaderboard',
    'leaderboard.tab.activity': 'My Activity',
    'leaderboard.tab.rewards': 'Rewards',
    'leaderboard.yourPosition': 'Your position',
    'leaderboard.points': 'points',
    'leaderboard.reviews': 'reviews',
    'leaderboard.prizesTitle': 'Prizes Available',
    'leaderboard.prizesDescription': 'The top 20 private users of the year will receive gift cards from €50 to €500. The leaderboard is public to ensure maximum transparency in the competition. Keep writing verified reviews to climb the leaderboard and win amazing prizes!',
    'leaderboard.top20': 'Top 20 Users',
    'leaderboard.filter.all': 'All',
    'leaderboard.filter.private': 'Private',
    'leaderboard.filter.business': 'Business',
    'leaderboard.noUsers': 'No users in leaderboard',
    'leaderboard.loading': 'Loading leaderboard...',
    'leaderboard.howToEarnCustomer': 'How to Earn Points - Private Users and Family Members',
    'leaderboard.howToEarnBusiness': 'How to Earn Points - Professionals',
    'leaderboard.allUsersEarn': 'All users (main profile and family members) earn points the same way:',
    'leaderboard.businessEarn': 'Professionals earn points based on customer reviews received and activities published.',
    'leaderboard.pointsNote': 'Review points are awarded after staff approval. Each user competes individually in the leaderboard, including family members.',
    'leaderboard.businessNote': 'Review points are awarded only after staff approval. The higher the quality of service, the more points earned.',

    // Points
    'points.completeReview': 'for complete review (with detailed ratings)',
    'points.referral': 'when a friend subscribes using your nickname',
    'points.basicReview': 'for basic review (final rating only)',
    'points.addBusiness': 'for adding a business not present',
    'points.addProduct': 'for each product added',
    'points.addClassified': 'for each ad published',
    'points.review1star': 'for 1-star review received',
    'points.review2star': 'for 2-star review received',
    'points.review3star': 'for 3-star review received',
    'points.review4star': 'for 4-star review received',
    'points.review5star': 'for 5-star review received',
    'points.jobPosting': 'for each job posting published',

    // Rewards
    'rewards.customersTitle': 'Rewards for Private Users',
    'rewards.customersDescription': 'The top 20 private users of the year will receive amazing gift card prizes.',
    'rewards.customersSubtitle': 'Keep earning points by writing verified reviews with photos and details. The greater your contribution to the community, the better your chances of winning!',
    'rewards.businessTitle': 'Rewards for Professionals',
    'rewards.businessDescription': 'The top 20 professionals of the year will receive special recognition for their excellence in customer service.',
    'rewards.businessSubtitle': 'Receive positive reviews and climb the leaderboard to gain visibility and exclusive rewards!',
    'rewards.1stPlace': '1st Place',
    'rewards.2ndPlace': '2nd Place',
    'rewards.3rdPlace': '3rd Place',
    'rewards.4to5Place': '4th - 5th Place',
    'rewards.6to10Place': '6th - 10th Place',
    'rewards.11to20Place': '11th - 20th Place',
    'rewards.2to5Place': '2nd - 5th Place',
    'rewards.6to20Place': '6th - 20th Place',
    'rewards.giftCard500': '€500 gift card',
    'rewards.giftCard200': '€200 gift card',
    'rewards.giftCard150': '€150 gift card',
    'rewards.giftCard100': '€100 gift card',
    'rewards.giftCard75': '€75 gift card',
    'rewards.giftCard50': '€50 gift card',
    'rewards.giftCardNote': 'Gift cards can be chosen from a list of brands and services that will be published later.',
    'rewards.excellenceCertificate': 'Excellence Certificate + Premium Visibility',
    'rewards.qualityBadge': 'Quality Badge + Premium Promotion',
    'rewards.recognitionBadge': 'Recognition Badge + Extra Visibility',
    'rewards.availableBadges': 'Available Badges',
    'rewards.pointsRequired': 'points required',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.back': 'Back',
    'common.view': 'View',
    'common.submit': 'Submit',
    'common.apply': 'Apply',

    // HomePage
    'home.welcomeTo': 'Welcome to',
    'home.platformName': 'Trovafacile',
    'home.tagline': 'The Italian platform that connects citizens and local businesses.',
    'home.subtitle': 'Verified reviews, products, classifieds, jobs and solidarity in one place.',
    'home.trialInfo': 'One month free trial for everyone! Then starting from €0.49/month for individuals and €2.49/month + VAT for businesses.',
    'home.startFree': 'Start Free',
    'home.viewPlans': 'View Plans',
    'home.whatCanYouDo': 'What you can do with Trovafacile',
    'home.completeDescription': 'A complete platform for all your daily needs',
    'home.feature.search.title': 'Search Businesses',
    'home.feature.search.description': 'Easily find commercial activities in your area. Search by category, city or name and discover the best services near you.',
    'home.feature.reviews.title': 'Verified Reviews',
    'home.feature.reviews.description': 'Read and write authentic reviews. Only verified users can leave feedback, ensuring maximum transparency and reliability.',
    'home.feature.prizes.title': 'Win Prizes',
    'home.feature.prizes.description': 'Write reviews and accumulate points! The top 20 users of the year win reloadable gift cards. The more reviews you write, the more prizes you win!',
    'home.feature.products.title': 'Local Products',
    'home.feature.products.description': 'Discover products from local businesses. Compare prices, read reviews and find exactly what you\'re looking for in your area.',
    'home.feature.classifieds.title': 'Free Classifieds',
    'home.feature.classifieds.description': 'Post and search for sale, exchange or donation ads. Connect with other users and exchange items in your community.',
    'home.feature.jobs.title': 'Job Offers',
    'home.feature.jobs.description': 'Find jobs or post listings. Businesses can find qualified candidates and workers can discover local opportunities.',
    'home.leaderboard.title': 'User Leaderboard with Exclusive Prizes',
    'home.leaderboard.description': 'Write reviews (individual users) and receive reviews (professionals) to climb the leaderboard! The top 20 users of the year will receive reloadable gift cards as a reward for their contribution. The more reviews you write with photos and details, the more points you earn!',
    'home.solidarity.title': 'Solidarity: 10% of Revenue to Charity',
    'home.solidarity.description1': 'Trovafacile donates every year',
    'home.solidarity.percentage': '10% of its revenue',
    'home.solidarity.description2': 'to non-profit associations and charity projects chosen by our members through a survey.',
    'home.solidarity.transparency': 'All documents certifying revenue and donations are published in the Solidarity section to ensure maximum transparency.',
    'home.forIndividuals': 'For Individuals',
    'home.forBusiness': 'For Businesses',
    'home.startingFrom': 'Starting from',
    'home.perMonth': '/month',
    'home.trialFree': 'One month free trial',
    'home.plusVAT': '+ VAT',
    'home.feature.findBusinesses': 'Find verified businesses in your area',
    'home.feature.findProducts': 'Find products of all kinds',
    'home.feature.writeReviews': 'Write reviews and win prizes',
    'home.feature.exclusiveDiscounts': 'Access exclusive business discounts',
    'home.feature.freeAds': 'Post free classifieds',
    'home.feature.jobSearch': 'Search for local job offers',
    'home.feature.charity': '10% will go to charity',
    'home.feature.increaseVisibility': 'Increase your business visibility',
    'home.feature.manageReviews': 'Manage reviews and respond to customers',
    'home.feature.addProducts': 'Add products and services to your showcase',
    'home.feature.exclusiveOffers': 'Create exclusive discounts for customers',
    'home.feature.publishJobs': 'Publish job offers and find staff',
    'home.feature.multipleLocations': 'Manage multiple locations from the same platform',
    'home.feature.analytics': 'Detailed statistics and analytics',
    'home.startNow': 'Start Now',
    'home.viewDetails': 'View Details',
    'home.topBusinesses': 'Top Rated Businesses',

    // ContactPage
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions or suggestions? We\'re here to help',
    'contact.email': 'Email',
    'contact.whatsapp': 'WhatsApp',
    'contact.hours': 'Support Hours',
    'contact.hoursCopy': 'Mon-Fri: 9:00 AM - 6:00 PM',
    'contact.faq': 'Frequently Asked Questions',

    // SubscriptionPage
    'subscription.title': 'Choose Your Plan',
    'subscription.subtitle': 'Start with 1 month free trial',
    'subscription.forCustomers': 'For Individuals',
    'subscription.forBusiness': 'For Businesses',
    'subscription.month': '/month',
    'subscription.popular': 'Popular',
    'subscription.current': 'Current Plan',
    'subscription.choosePlan': 'Choose Plan',
    'subscription.features': 'Features',
    'subscription.trialNote': 'All plans include 1 month free trial',

    // RulesPage
    'rules.title': 'Platform Rules',
    'rules.subtitle': 'Guidelines for using Trovafacile',
    'rules.conduct': 'Code of Conduct',
    'rules.reviews': 'Reviews',
    'rules.businesses': 'Businesses',
    'rules.privacy': 'Privacy and Security',

    // ProfilePage
    'profile.title': 'My Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.editProfile': 'Edit Profile',
    'profile.familyMembers': 'Family Members',
    'profile.addMember': 'Add Member',
    'profile.businessInfo': 'Business Information',
    'profile.locations': 'Locations',
    'profile.subscription': 'Subscription',
    'profile.settings': 'Settings',
    'profile.logout': 'Logout',

    // DashboardPage
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Overview',
    'dashboard.stats': 'Statistics',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.reviews': 'Reviews',
    'dashboard.products': 'Products',
    'dashboard.classifieds': 'Classifieds',
    'dashboard.jobs': 'Job Offers',
    'dashboard.discounts': 'Discounts',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'it';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['it']] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
